# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: Templates # In a different organization
    type: git
    name: Sentinel-ContentAsCode/Templates
#    endpoint: eran-test-service-connection

steps:
- checkout: self  
- checkout: Templates
  persistCredentials: true

- script: |
    echo "Starting script"
    echo "DIR"
    dir $(Build.SourcesDirectory)
    git config --global user.email "ertoleda@microsoft.com"
    git config --global user.name "Eran"
    cd $(Build.SourcesDirectory)/Templates
    echo "git remote -v"
    git remote -v
    echo "git checkout branch"
    git checkout -b testBranch
    echo "test" > test.txt
    git add test.txt
    git commit -m "test commit"
    git push origin testBranch
