# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: Templates # In a different organization
    type: git
    name: Sentinel-ContentAsCode/Templates
#    endpoint: eran-test-service-connection

steps:
- checkout: Templates

- script: |
  echo "Starting script"
  dir $(Build.SourcesDirectory)
  cd $(Build.SourcesDirectory)/Templates
  git remote -v
  git checkout -b testBranch
  echo "test" > test.txt
  git add test.txt
  git commit -m "test commit"
  git push origin testBranch
