# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: Templates # In a different organization
    endpoint: eran-test-service-connection
    type: git
    name: Sentinel-ContentAsCode/Templates


steps:
- checkout: Templates

