# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  targetProjectName: Sentinel-ContentAsCode
  targetRepoName: Templates

resources:
  repositories:
  - repository: $(targetRepoName)
    type: git
    name: $(targetProjectName)/$(targetRepoName)

jobs:
- job: CreatePullRequest
  pool:
    vmImage: ubuntu-latest
  
  steps:
  - checkout: self  
  - checkout: $(targetRepoName)
    persistCredentials: true
  
  - powershell: |
      $date=$(Get-Date -Format "yyyyMMdd_HHmm");
      $branchName = "branchName_$date"
      Write-Host "BranchName: $branchName"
      Write-Host "##vso[task.setvariable variable=branchName]$branchName"

  - script: |
      echo "Starting script"
      git config --global user.email "ertoleda@microsoft.com"
      git config --global user.name "Eran"
      cd $(Build.SourcesDirectory)/Templates
      echo "git remote -v"
      git remote -v
      echo "git checkout branch"
      git checkout -b $(branchName)
      echo "test" > test.txt
      git add test.txt
      git commit -m "test commit"
      git push origin $(branchName)

  - task: PowerShell@2
    env:
      SYSTEM_ACCESSTOKEN: $(system.accesstoken)
      SYSTEM_TEAMPROJECT: $(System.TeamProject)
      SYSTEM_COLLECTIONURI: $(System.CollectionUri)
      BUILD_REPONAME: $(targetRepoName)
    inputs:
      targetType: 'filePath'
      filePath: Templates/Scripts/CreatePRBuildTask.ps1

