name: Sync Repos

on:
  push:
    branches:
      - main


jobs:
  sync-repos:
    runs-on: windows-latest
    env:
      devopsToken: ${{ secrets.AZURE_DEVOPS_TOKEN }}
      directory: ${{ github.workspace }} 
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Sync Repos
      shell: pwsh
      run: |
        ${{ github.workspace }}\Scripts\sync.ps1

#sync:
#        name: Execute Powershell
#        runs-on: ubuntu-latest
#        steps:
#        - name: Azure Pipelines Action
#          uses: Azure/pipelines@v1
#          with:
#            azure-devops-project-url: https://dev.azure.com/sentinel-eco-devs/Sentinel-ContentAsCode
#            azure-pipeline-name: 'erant10.templates'
#            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
