name: CI

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  push:
    branches:
      - main

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/sentinel-eco-devs/Sentinel-ContentAsCode
            azure-pipeline-name: 'erant10.templates'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
